version: 2
updates:
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: weekly
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: docker
    schedule:
      interval: weekly
