// Copyright 2021 Northern.tech AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Code generated by mockery v2.2.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AreDevicesInGroup provides a mock function with given fields: ctx, devices, group
func (_m *Client) AreDevicesInGroup(ctx context.Context, devices []string, group string) (bool, error) {
	ret := _m.Called(ctx, devices, group)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) bool); ok {
		r0 = rf(ctx, devices, group)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, devices, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
