# coding: utf-8

"""
    Device Configure Management API

    API for managing persistent device connections. Intended for use by the web GUI   # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@mender.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import management_api
from management_api.api.management_api_client import ManagementAPIClient  # noqa: E501
from management_api.rest import ApiException


class TestManagementAPIClient(unittest.TestCase):
    """ManagementAPIClient unit test stubs"""

    def setUp(self):
        self.api = management_api.api.management_api_client.ManagementAPIClient()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_parameters(self):
        """Test case for list_parameters

        Get existing parameters  # noqa: E501
        """
        pass

    def test_set_configuration(self):
        """Test case for set_configuration

        Assign configuration parameters  # noqa: E501
        """
        pass

    def test_unset_configuration(self):
        """Test case for unset_configuration

        Assign configuration parameters  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
