# coding: utf-8

# flake8: noqa
"""
    Device Configure Management API

    API for managing persistent device connections. Intended for use by the web GUI   # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@mender.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from management_api.models.error import Error
from management_api.models.parameter import Parameter
