openapi: 3.0.3

info:
  title: Device Configure Devices API
  description: |
    Device facing API for managing persistent device connections.

  version: "1"

  contact:
    name: Mender Support
    email: support@mender.io
    url: https://mender.io/contact-us

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://hosted.mender.io/api/devices/v1/deviceconfig

# Global security definitions
security:
  - DeviceJWT: []

tags:
  - name: DevicesAPI

paths: {} # TBD
